# Generated by Django 5.0.2 on 2024-12-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customuser_role_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('transportation', 'Transportation'), ('real_estate', 'Real Estate'), ('electronics', 'Electronics'), ('clothes', 'Clothes'), ('hobby_entertainment', 'Hobby and Entertainment'), ('others', 'Others')], max_length=50),
        ),
    ]
